{
 "title": "HLF Metrics",
 "description": "View of Fabric Peer and Orderer Metrics",
 "time": { "from": "2022-08-10T15:06:58.677Z", "to": "2022-08-10T15:29:33.864Z" },
 "templating": {
  "list": [
   { "name": "containergroup", "label": "Container Group", "query": { "query": "label_values(container_group)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": {
     "query": "label_values(node_boot_time, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Gossip Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gossip Validation Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(gossip_privdata_validation_duration_sum[$interval])/rate(gossip_privdata_validation_duration_count[$interval])*1000) without (instance,channel)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Gossip Payload Buffer Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(gossip_payload_buffer_size) without (instance,channel)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Gossip Commit Block Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(gossip_privdata_commit_block_duration_sum[$interval])/rate(gossip_privdata_commit_block_duration_count[$interval])*1000) without (instance,channel)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Chaincode Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job, chaincode) (rate(chaincode_shim_request_duration_sum{chaincode!~\"_lifecycle.*|cscc|qscc\"}[$interval])) / sum by(job, chaincode) (rate(chaincode_shim_request_duration_count{chaincode!~\"_lifecycle.*|cscc|qscc\"}[$interval]))",
     "legendFormat": " {{job}} {{chaincode}}"
    }
   ]
  },
  {
   "title": "Request Received",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(channel,type) (rate(chaincode_shim_requests_received{chaincode!~\"_lifecycle.*|cscc|qscc\"}[$interval]))",
     "legendFormat": "{{job}} {{chaincode}}"
    }
   ]
  },
  {
   "title": "Requests Completed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (chaincode,job) (rate(chaincode_shim_requests_completed{chaincode!~\"_lifecycle.*|cscc|qscc\"}[$interval]))",
     "legendFormat": "{{job}} {{chaincode}}"
    }
   ]
  },
  { "title": "Endorser Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Successful Proposal Duration",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(channel, chaincode) (rate(endorser_proposal_duration_sum{chaincode!~\"cscc|qscc|_lifecycle.*\",success=\"true\"}[$interval])) / sum without(channel, chaincode) (rate(endorser_proposal_duration_count{chaincode!~\"cscc|qscc|_lifecycle.*\",success=\"true\"}[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Proposal Received",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(endorser_proposals_received[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Successful Proposals",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(endorser_successful_proposals[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Ledger Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Block  Storage Commit Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(channel) (rate(ledger_blockstorage_commit_time_sum[$interval])) / sum without(channel) (rate(ledger_blockstorage_commit_time_count[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(channel) (rate(ledger_block_processing_time_sum[$interval])) / sum without(channel) (rate(ledger_block_processing_time_count[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "StateDB Commit Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum without(channel) (rate(ledger_statedb_commit_time_sum[$interval])) / sum without(channel) (rate(ledger_statedb_commit_time_count[$interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Blockchain height",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 34 },
   "targets": [
    { "expr": "ledger_blockchain_height", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "blockheight rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "(sum(irate(ledger_blockchain_height[$interval])) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}