global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "orderer"
    static_configs:
      - targets: ["localhost:9443"]
  - job_name: "peer0_org1"
    static_configs:
      - targets: ["localhost:9444"]
  - job_name: "peer0_org2"
    static_configs:
      - targets: ["localhost:9445"]
  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
  - job_name: process
    static_configs:
      - targets: ['localhost:9256']
