global:
  scrape_interval: 1s
  external_labels:
    monitor: 'devopsage-monitor'

scrape_configs:
# sut ip address + orderer port (how many orderers ?)
  - job_name: "orderer"
    static_configs:
      - targets: ["localhost:9443"]
# sut ip address + peer port (how many peers ?)
  - job_name: "peer0_org1"
    static_configs:
      - targets: ["localhost:9444"]
# sut ip address + peer port (how many peers ?)
  - job_name: "peer0_org2"
    static_configs:
      - targets: ["localhost:9445"]
# sut ip address
  - job_name: node
    static_configs:
      - targets: ['localhost:9100']
# sut ip address
  - job_name: process
    static_configs:
      - targets: ['localhost:9256']
# push gateway is local to prometheus
# workers need to be configured through a benchmark (yuck)
  - job_name: caliper
    static_configs:
      - targets: ['localhost:9091']