go_name: 'go{{go_ver}}.{{go_platform}}'
go_tgz: '{{go_name}}.tar.gz'

# https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz
go_tgz_url: https://dl.google.com/go/{{go_tgz}}
go_checksum: '{{go_checksums[go_ver][go_platform]}}'
go_dir: '{{go_parent_dir}}/{{go_name}}'

# Don't need
# go_root: '{{go_parent_dir}}/go'
# go_path: '{{home_dir}}/gopath'

go_checksums:
  1.18.6:
    darwin-amd64: sha256:05ef7855970fd9caf4e8d34fe73146cffcff740b80d00189d129302f13d22e6b
    linux-amd64: sha256:bb05f179a773fed60c6a454a24141aaa7e71edfd0f2d465ad610a3b8f1dc7fe8
  1.18.3:
    darwin-amd64: sha256:d9dcf8fc35da54c6f259be41954783a9f4984945a855d03a003a7fd6ea4c5ca1
    linux-amd64: sha256:956f8507b302ab0bb747613695cdae10af99bbd39a90cae522b7c0302cc27245
