- name: Check if already installed.
  become: true
  become_flags: -H
  shell: "docker --version"
  register: docker_version_check
  ignore_errors: true

- name: If installation doesn't already exist, install now.
  when: docker_version_check.rc != 0
  become: true
  block:
    - name: Add Docker's GPG key
      apt_key:
        url: '{{docker_gpg_key_url}}'
        state: present

    - name: Add the Docker (stable) repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

# Fyre having issues with dockerhub rate limit
#    - name: Test run with hello-world
#      shell: docker run hello-world

# - name: Check if docker-compose is installed
#  become: true
#  become_flags: -H
#  shell: "docker-compose --version"
#  register: docker_compose_version_check
#  ignore_errors: true

# - name: Install docker compose
#  when: docker_compose_version_check.rc != 0
#  block:
#    - name: Download the docker-compose binary
#      get_url:
#        url: 'https://github.com/docker/compose/releases/download/{{docker_compose_version}}/docker-compose-Linux-x86_64'
#        dest: /usr/local/bin/docker-compose
#    - name: Chmod +x to the file
#      file:
#        dest: /usr/local/bin/docker-compose
#        mode: +x