#!/usr/bin/env ansible-playbook

# Example playbook runner to stand up a fabric platform for docker
# it still contains the ability to control each play but
# usually always use the -e "plays=all"

- import_playbook: playbooks/5-docker-prereqs.yaml
  when: '"docker" in plays'

- import_playbook: playbooks/5-vm-prereqs.yaml
  when: '"vm" in plays'

- import_playbook: playbooks/10-common-prereqs.yaml
  when: '"prereqs" in plays'

- import_playbook: playbooks/15-deploy-prometheus.yaml
  when: '"deployprom" in plays'

- import_playbook: playbooks/20-checkout-and-build-fabric.yaml

- import_playbook: playbooks/30-checkout-chaincode.yaml

- import_playbook: playbooks/40-generate-crypto-fabric.yaml

- import_playbook: playbooks/45-copy-crypto.yaml

- import_playbook: playbooks/47-deploy-caliper.yaml
  when: '"caliper" in plays'

- import_playbook: playbooks/50-generate-channel.yaml

- import_playbook: playbooks/55-restart-fabric-nodes.yaml

- import_playbook: playbooks/60-create-channels.yaml
  when: 'plays=="all" or ("createchan" in plays)'

- import_playbook: playbooks/65-create-anchors.yaml

- import_playbook: playbooks/70-lscc-deploy-chaincode.yaml

