{
 "title": "Node Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Orderer Nodes Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Orderer CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (job)(irate(node_cpu_seconds_total{job=~\"node\", mode=\"idle\"}[$__interval])) * 100)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Orderer Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=~\"node\"} - node_memory_MemAvailable_bytes{job=~\"node\"}) / node_memory_MemTotal_bytes{job=~\"node\"}) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Orderer Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job)((node_filesystem_size_bytes{job=~\"node\"} - node_filesystem_free_bytes{job=~\"node\"} )/ node_filesystem_size_bytes{job=~\"node\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=~\"node\",device!=\"sr0\"}[$__interval])",
     "legendFormat": "read-{{job}}-{{device}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=~\"node\",device!=\"sr0\"}[$__interval])",
     "legendFormat": "write-{{job}}-{{device}}"
    }
   ]
  },
  {
   "title": "Peer Nodes Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Peer CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (job)(irate(node_cpu_seconds_total{job=~\"node\", mode=\"idle\"}[$__interval])) * 100)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Peer Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=~\"node\"} - node_memory_MemAvailable_bytes{job=~\"node\"}) / node_memory_MemTotal_bytes{job=~\"node\"}) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Peer Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job)((node_filesystem_size_bytes{job=~\"node\"} - node_filesystem_free_bytes{job=~\"node\"} )/ node_filesystem_size_bytes{job=~\"node\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=~\"node\",device!=\"sr0\"}[$__interval])",
     "legendFormat": "read-{{job}}-{{device}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=~\"node\",device!=\"sr0\"}[$__interval])",
     "legendFormat": "write-{{job}}-{{device}}"
    }
   ]
  },
  {
   "title": "Client Nodes Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "Client CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (job)(irate(node_cpu_seconds_total{job=~\"node\", mode=\"idle\"}[$__interval])) * 100)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Client Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=~\"node\"} - node_memory_MemAvailable_bytes{job=~\"node\"}) / node_memory_MemTotal_bytes{job=~\"node\"}) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Client Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job)((node_filesystem_size_bytes{job=~\"node\"} - node_filesystem_free_bytes{job=~\"node\"} )/ node_filesystem_size_bytes{job=~\"node\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=~\"node\",device!=\"sr0\"}[$__interval])",
     "legendFormat": "read-{{job}}-{{device}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=~\"node\",device!=\"sr0\"}[$__interval])",
     "legendFormat": "write-{{job}}-{{device}}"
    }
   ]
  }
 ]
}