__peer_org: '{{ group_names | difference("peers") | first }}'
__peer_name: '{{ inventory_hostname }}'

# this is the core_peer_gossip_bootstrap variable. Computed by finding all  peers of same org minus the peer itself,
# returning the first of them


__other_peers: '{{ groups[__peer_org] | difference(__peer_name) }}'
# can't use 0.0.0.0 for itself as TLS complains
# peer_gossip_bootstrap: '{{ hostvars[( __other_peers | first)].ansible_host if (__other_peers | length > 0) else "0.0.0.0" }}:7051'
peer_gossip_bootstrap: '{{ hostvars[( __other_peers | first)].ansible_host if (__other_peers | length > 0) else hostvars[__peer_name].ansible_host }}:7051'

peer_mspid: '{{ __peer_org }}MSP'
peer_mspdir: /root/crypto-config/peerOrganizations/{{__peer_org}}/peers/{{ __peer_name }}/msp/
peer_tls_privkey: /root/crypto-config/peerOrganizations/{{__peer_org}}/peers/{{ __peer_name }}/tls/server.key
peer_tls_cert: /root/crypto-config/peerOrganizations/{{__peer_org}}/peers/{{ __peer_name }}/tls/server.crt
peer_tls_rootcas: /root/crypto-config/peerOrganizations/{{__peer_org}}/peers/{{ __peer_name }}/tls/ca.crt
