#!/usr/bin/env ansible-playbook
# TODO: Improve performance only build the needed binaries on each of the systems, not all systems

- name: Checkout the fabric-smart-client or fabric-token application
  hosts: fsc
  remote_user: root

  vars:
    target: '{{ "orderer" if "orderers" in group_names else "peer" }}' # == 'peer' if it's client as well.

  tasks:
    - name: Checkout to the {{fscBranch}} branch
      git:
        dest: '{{ fscDest }}'
        repo: '{{fscRepo}}'
        version: '{{fscBranch}}'
        update: yes

    - name: Remove existing fsc node binaries
      make:
        chdir: '{{ fscDest }}/{{ fscPath }}'
        target: 'clean'

    # TODO should only do the appropriate one for the node but will do all for now
    - name: Build the appropriate node binary
      make:
        chdir: '{{ fscDest }}/{{ fscPath }}'
        target: 'nodes'




