#!/usr/bin/env ansible-playbook

- name: Create ordererOrgs and peerOrgs maps to be used for following plays
  hosts: clients
  remote_user: root

  roles:
    - util/orgvars

- name: Generate crypto materials on the Client
  # `hosts` could simply be client0, but thing is, we need ansible facts of other hosts
  # specifically IP addresses of peers and orderers for generating crypto config.
  # And ansible is being weird and not letting us access the facts unless the play is run for
  # all hosts
  hosts: client0:peers:orderers
  remote_user: root

  roles:
    - role: util/ensure_empty_folder
      path: /root/crypto-config

  tasks:
    - name: Fill templates of crypto-config.yaml.j2
      template:
          dest: /root/crypto-config.yaml
          src: ./templates/crypto-config.yaml.j2
      when: 'inventory_hostname == "client0"'

    - name: Run cryptogen
      shell: PATH={{ dltDest }}/build/bin cryptogen generate --config=/root/crypto-config.yaml
      args:
        chdir: /root
      when: 'inventory_hostname == "client0"'

- name: Copy Crypto materials from client0 to all peers, orderers and other clients (caliper workers use path references)
  hosts: clients:peers:orderers
  remote_user: root

  roles:
    - role: util/copy_remote_to_remotes
      src: /root/crypto-config
      src_hostname: 'client0'
      dest_groups: [clients, peers, orderers]
