#!/usr/bin/env ansible-playbook

- name: Create ordererOrgs and peerOrgs maps to be used for following plays
  hosts: client0
  remote_user: root

  roles:
    - util/orgvars
    - util/fscvars

- name: Generate fsc crypto materials on the Main Client
  # `hosts` could simply be client0, but thing is, we need ansible facts of other hosts
  # specifically IP addresses of peers and orderers for generating crypto config.
  # And ansible is being weird and not letting us access the facts unless the play is run for
  # all hosts
  hosts: all
  remote_user: root

  tasks:
    - name: generate crypto-config-fsc-extend.yaml to extend fabric crypto to include fsc nodes in their owning orgs (fabric-driver)
      template:
          dest: /root/crypto-config-fsc-extend.yaml
          src: ./templates/crypto-config-fsc-extend.yaml.j2
      when: 'inventory_hostname == "client0"'

    - name: Run cryptogen to extend fabric crypto material
      shell: PATH={{ dltDest }}/build/bin cryptogen extend --input=/root/crypto-config --config=/root/crypto-config-fsc-extend.yaml
      args:
        chdir: /root
      when: 'inventory_hostname == "client0"'

    - name: delete concatenated cacerts file if it exists
      shell: rm /root/crypto-config/cacerts.pem | true
      when: 'inventory_hostname == "client0"'

    - name: create the concatenated cacerts file for all fabric organisations
      shell: cat /root/crypto-config/peerOrganizations/{{item}}/msp/tlscacerts/tlsca.{{item}}-cert.pem >> /root/crypto-config/cacerts.pem
      loop: "{{orgvars_peerOrgsList}}"
      when: 'inventory_hostname == "client0"'

    - name: generate crypto-config-fsc.yaml to create a single organisation for all the fsc nodes (holds their unique identities under a single org)
      template:
          dest: /root/crypto-config-fsc.yaml
          src: ./templates/crypto-config-fsc.yaml.j2
      when: 'inventory_hostname == "client0"'

    - name: Run cryptogen to generate fsc crypto material
      shell: PATH={{ dltDest }}/build/bin cryptogen generate --config=/root/crypto-config-fsc.yaml
      args:
        chdir: /root
      when: 'inventory_hostname == "client0"'
