# The following variables are optional, and organized by playbooks. You can override them via command line.

# initial-setup.yaml
# None

# generate-crypto.yaml
# None

# checkout-and-build.yaml
dltRepo: https://github.com/hyperledger/fabric
dltBranch: main
dltDest: /root/src/github.com/hyperledger/fabric

# checkout-benchmarks
benchDest: '/root/caliper-benchmarks'
benchRepo: https://github.com/hyperledger/caliper-benchmarks
benchBranch: 'main'

# generate-channel.yaml
channelIDs: ch1 # comma separated string of channel names (e.g. ch1,ch2,ch3)
channelPeerAlloc: all # defaults to all, but can be set as a dict from channelName to a list of peers belonging to that channel
channelOrdererAlloc: all # defaults to all, but can be set as a dict from channelName to a list of orderers belonging to that channel
block_cut_time: 1s
block_size: 50
preferred_max_bytes: 512 KB

# lscc-deploy-chaincode.yaml
# channelIDs: ch1  -- not writing because already defined above.
ccName: fixed-asset
ccVersion: 1.0.2
# has to be available on the peer (what is the path relative to ?) and is pre-vendored
ccPath: '{{ benchDest }}/src/fabric/api/fixed-asset-base/go'
endorsementPolicy: 'OR ("peerOrg0MSP.member","peerOrg1MSP.member")'
ccInitArgs: '{"Args": ["init"]}'
ccQueryArgs: '{"Args": ["emptycontract"]}'

enable_profile: true

# Resource control
peerActiveCPUs: "{{ ansible_processor_vcpus | int }}"
peerTotalCPUs: 2
ordererActiveCPUs: "{{ ansible_processor_vcpus | int }}"
ordererTotalCPUs: 2

# Defaults when launching site.yaml on it's own
plays:
  # - docker          # setting this off by default as it won't be needed in most cases
  # - vm            # note defined in site.yaml currently
  # - prereqs
  # - gencrypto     # setting this off by default as it won't be needed in most cases
  # - genchan       # not needed in most cases
  - checkoutdlt         # needed in most cases
  - checkoutbench       # needed in most cases
  - downnodes       # needed in most cases
  - upnodes         # needed in most cases
  - createchan      # needed in most cases
  - createanch
  - installcc       # needed in most cases

###############################################################
# WARNING: Don't mess with any of the following.
###############################################################
ansible_python_interpreter: python3
ansible_connection: docker

channelIDsList: "{{ channelIDs.split(',') }}"
orderers: '{{ groups["orderers"] }}'
peers: '{{ groups["peers"] }}'
clients: '{{ groups["clients"] }}'

fabric_cfg_path: '/{{ dltDest }}/sampleconfig'
