- name: Check if already installed.
  become: true
  stat:
    path: '{{go_dir}}'
  changed_when: False
  register: go_binary

- name: If installation doesn't already exist, install now.
  when: go_binary.stat.islnk is not defined
  block:
    - name: Download go archive
      get_url:
        url: '{{go_tgz_url}}'
        dest: /tmp/{{go_tgz}}
        checksum: '{{go_checksum}}'
        mode: '0644'

    - name: Create Go version directory
      file:
        path: '{{go_dir}}'
        state: directory
        mode: '0755'

    - name: Unarchive go
      unarchive:
        copy: no
        src: /tmp/{{go_tgz}}
        dest: '{{go_dir}}'
        creates: '{{go_dir}}/go'

    - name: Link in latest go
      become: true
      file:
        src: '{{go_dir}}/go'
        dest: '{{go_parent_dir}}/go'
        state: link

# required for docker containers will also use for VMs so no need for gopath, goroot assume the default
    - name: Link latest go binary to usr/bin
      become: true
      file:
        src: '{{go_dir}}/go/bin/go'
        dest: '/usr/bin/go'
        state: link

# only works for VMs, doesn't work for docker containers, but it's now redundant
#    - name: Set bash environment variables
#      block:
#        - name: Make sure ~/.bashrc exists
#          file:
#            path: '{{ home_dir }}/.bashrc'
#            state: file
#            mode: '0600'

#        - name: Create gopath
#          file:
#            path: '{{ go_path }}'
#            state: directory
#            mode: '0655'

#        - name: Add environment variables to ~/.bashrc
#          lineinfile:
#            dest: '{{ home_dir }}/.bashrc'
#            line: "{{ item }}"
#            state: present
#          with_items:
#            - export GOROOT='{{ go_root }}'
#            - export GOPATH='{{ go_path }}'
#            - export PATH="$PATH:${GOROOT}/bin"
#            - export PATH="$PATH:${GOPATH}/bin"

#    - name: Set environment variables
#      block:
#        - name: Create gopath
#          file:
#            path: '{{ go_path }}'
#            state: directory
#            mode: '0655'

#        - name: Add Go paths as permantent env vars
#          copy:
#            dest: /etc/profile.d/gopath-vars.sh
#            content: |
#              export GOROOT={{ go_root }}
#              export GOPATH={{ go_path }}
#              export PATH=$PATH:${GOPATH}/bin:${GOROOT}/bin

  always:
    - name: Cleanup
      file:
        path: /tmp/{{go_tgz}}
        state: absent
