all:
    children:
        peers: # group name
            children:
                # this is the MSP id and represents an org
                peerOrg0: # group name
                    hosts:
                        peer0: { ansible_host: peer0}
                peerOrg1:
                    hosts:
                        peer1: { ansible_host: peer1 }
                peerOrg2:
                    hosts:
                        peer2: { ansible_host: peer2 }
        orderers:
            children:
                ordererOrg0:
                    hosts:
                        orderer0: { ansible_host: orderer0 }
#                        orderer1: { ansible_host: orderer1 }
#                        orderer2: { ansible_host: orderer2 }
        clients:
            hosts:
                 client0: { ansible_host: client0 }
                 client1: { ansible_host: client1 }

        fsc:
            children:
                issuer: # role name, must have a make target
                    vars:
                        owning_org: peerOrg0
                    hosts:
                        issuer0: { ansible_host: issuer0 }
                alice: # role name, must have a make target
                    vars:
                        owning_org: peerOrg1
                        idemix: true
                    hosts:
                        alice0: { ansible_host: alice0 }
                bob: # role name, must have a make target
                    vars:
                        owning_org: peerOrg1
                        idemix: true
                    hosts:
                        bob0: { ansible_host: bob0 }

                approver: # role name, must have a make target
                    vars:
                        owning_org: peerOrg2
                        is_bootstrap: true
                    hosts:
                        approver0: { ansible_host: approver0 }
                client: # role name, must have a make target
                    vars:
                        owning_org: peerOrg0
                    hosts:
                        client1: { ansible_host: client1 }

